name: habitos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0 
  shared_preferences: ^2.2.2
  uuid: ^4.5.2
  fl_chart: ^1.1.1
  drift: ^2.11.0
  path_provider: ^2.0.14
  file_picker: ^5.3.2
  get_it: ^9.1.1
  path: ^1.9.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 
  drift_dev: ^2.11.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true